name: Kits
main: dev.foolen.kits.Kits
version: 1.0
api-version: 1.13

commands:
  kits:
    usage: /<command>
    description: shows all available kits
  kit:
    usage: /<command> [kit-name]
    description: uses a specified kit