name: Kits
main: dev.foolen.kits.Kits
version: 0.1

commands:
  kits:
    usage: /<command>
    description: shows all available kits
  kit:
    usage: /<command> [kit-name]
    description: uses a specified kit